language: java
install: TERM=dumb gradle setupCIWorkspace
script: TERM=dumb gradle build
after_success:
- TERM=dumb gradle ftpRelease
- TERM=dumb gradle downloadPage
env:
  global:
  - secure: aQJpNBZR5P83afKnkHmn/SvT5wIIX126zPDX/sejPUSWrlN3j90FjxXovrVZLsVoLM2HU1GoRCPXU2/Tb1fV1FljJ+uNAVoGFtjfGzJLcKu6hrVBIq9P2w1yxtq3uy1lRz5Z0evgTACA04dP8a78xsjqGwhYMWte4QZrVy7DNVQ=
  - secure: j98Ry4zrU4I3rrQhpO8VITeySocasqIlBL1jrHBVvugr395ExIinLuuL6vDRSX04ZJsDXLjDvjlgy4MX0QKIbhSKr87Vqlf2/fEEpR/2Mig2RqF+zfG0ZJYZd4qnL9kJZm0MjsVd8QSWgOlFY4ohuunGkoCic1+7oSWcpJP7J1Y=
  - secure: afx592CfDA5XDie9frblXYyCkVZFYab1RCKwDFp68+5E2NLNzGsyv/yYuJ9Fw4M8K/3Xhq4kzVrRcfsvo3FJpeEwvs+lEkEitv621sWGATMy1FTipVMEUMAKPXQAYJRsILEDbpZcd0D1prJRAyKzIokLtQs524FhJXRgt8OzGtY=
  - secure: 8OnozEsM3kDYL0ShMFHPp1DS4+jg316pZAqcNY5hG8gnHbxTsjy3cj9G3roCj11U5D5cE5bASr1sD0BLZsvsHX+bJn6gRpTx2AG5wEY9A05uoGTmssoDh0ObiuSZzoZD9X0mfLsaGqGD77W9EuimC0JJX1iEMgzSecn8qGrAql4=
