language: java
install: TERM=dumb gradle setupCIWorkspace --stacktrace
script: TERM=dumb gradle build --stacktrace
after_success:
- TERM=dumb gradle uploadFTP --stacktrace
- TERM=dumb gradle updateDownloadPage --stacktrace
env:
  global:
  - secure: MSLgdqhk9iOTvkRjeeWVQq8m0/uf3jaMWkKY07VUdi0hhXOB1J7P2EzbWepaWXKpN98irYdOwMjLjc7l1o7tdoHbVQLIkbuacBFrNGFwZdp9WM7gSfSdjBuQN+h9f+girz0ibUvUmM1bfxMVTr4T2u+OhB8E3pdOMwJI3gYl+MY=
  - secure: wT8V8l00NGeHHnavgFalac+yCRzdYck5F1fEKIuQ63RbCNE5/xT5FGAHSBIEQfNNBKTD9q2rakcRk+WLuDXeCSaQq8ZwNqWQ1O3SKvEmRrn6NFTX/FBGk3VMtoFlNpSgIqx9AbcdWx+NbjV7xkEIz6RwOvlv4FDSfq6LEw36L+c=
  - secure: JjPcDWJdJuVZynihiqduQZ5MG/GutRE8XygiZ/MwOqopbsdeveSywLgtIWu2oTAX5q/9NQIUmFz5ybM7F2C/Y89j/6rxSFivQ6iBWcLatVhtWlf9BwbgP+ecYT68Jzxc8+OTPFl13ncRicgJ2aVaNLgDBsXJLKIhvSqYKXczhKc=
  - secure: hjUgqKTB2c8Azr/OA38lmlM6N2eJnLMAnbhzeN7EPza4bm7LHFScSlsb7Hn0yHRNPwNYVYWyy+AqN4sGpAEvIHdKEpy0oJ0n4lfLjiHc/J9p+gJYIMFBZQ9FrpCRin/VeLl3dgBdRvEmDVO60triVH9pl7X/rSgZju/xGz1xUB8=
